// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_PCC.Models;

public partial class AFamily
{
    public int Id { get; set; }

    public int? AnimalId { get; set; }

    public int? SireId { get; set; }

    public int? DamId { get; set; }

    public int? Status { get; set; }

    public bool? DeleteFlag { get; set; }

    public string DeletedBy { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public DateTime? DateDeleted { get; set; }

    public DateTime? DateRestored { get; set; }

    public string RestoredBy { get; set; }
}