// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_PCC.EntityModels;

public partial class TblAudittrail
{
    public int Id { get; set; }

    public string Actions { get; set; }

    public string Module { get; set; }

    public DateTime? DateCreated { get; set; }

    public string UserId { get; set; }

    public int? Status { get; set; }
}