// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_PCC.Models;

public partial class TblDamModel
{
    public int Id { get; set; }

    public string DamRegistrationNumber { get; set; }

    public string DamIdNumber { get; set; }

    public string DamName { get; set; }

    public string BreedCode { get; set; }

    public string BloodCode { get; set; }
}