// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_PCC.Models;

public partial class TblJoinBuffHerd
{
    public int JoinBuffHerdId { get; set; }

    public int BuffaloTypeId { get; set; }

    public int BuffHerdId { get; set; }

    public int FeedingSystemId { get; set; }
}