// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_PCC.Models;

public partial class TblOriginOfAcquisitionModel
{
    public int Id { get; set; }

    public string City { get; set; }

    public string Province { get; set; }

    public string Barangay { get; set; }

    public string Region { get; set; }
}