// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_PCC.Models;

public partial class TblRegistrationOtpmodel
{
    public int Id { get; set; }

    public string Email { get; set; }

    public string Otp { get; set; }

    public int? Status { get; set; }
}