// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_PCC.EntityModels;

public partial class TblSireModel
{
    public int Id { get; set; }

    public string SireRegistrationNumber { get; set; }

    public string SireIdNumber { get; set; }

    public string SireName { get; set; }

    public string BreedCode { get; set; }

    public string BloodCode { get; set; }
}