// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_PCC.Models;

public partial class TblTokenModel
{
    public int Id { get; set; }

    public string Token { get; set; }

    public DateTime ExpiryDate { get; set; }

    public string Status { get; set; }

    public DateTime DateCreated { get; set; }
}