// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
namespace API_PCC.EntityModels;

public partial class UserModuleTable
{
    public int Id { get; set; }

    public string Module { get; set; }

    public int? ParentModule { get; set; }

    public DateTime? DateCreated { get; set; }
}