// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_PCC.EntityModels;

public partial class FarmFeedingSystem
{
    public int Id { get; set; }

    public int? Farmer_Id { get; set; }

    public int? FeedingSystem_Id { get; set; }

    public int? Created_By { get; set; }

    public DateTime? Created_At { get; set; }

    public int? Deleted_By { get; set; }

    public bool? Is_Deleted { get; set; }

}