// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_PCC.Models;

public partial class TblAttempt
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public int? AttemptCount { get; set; }

    public string Ipaddress { get; set; }

    public string Location { get; set; }
}